### ISSUE TITLE
Style inline audio player progress bar properly over a line break

### ISSUE THREAD

**Issue by joannaskao** [Financial-Times/g-audio#1]

**Comment by aendra-rininsland** [comment]
This is due to `height: 100%` on the absolute positioned element:

![screen shot 2017-01-04 at 17 26 42](https://cloud.githubusercontent.com/assets/185041/21652065/0b8da8c4-d2a3-11e6-9ece-4aba524452eb.png)

To resolve, either set height to the lineheight of the containing element, or use the linear-gradient approach you mentioned earlier.

**Comment by joannaskao** [comment]
Fixed with 7a2621765bca0bad3036c2d5f736992c871c9040 and 979e8abe2e1ac12d063e120a8a2a9537a40d0e1b
